### PR TITLE
Avoid wrapping handler twice in DebuggedApplication

### PR DESCRIPTION
**Pull request by kkroboth**

### CODE REVIEW

**Comment by tony** [comment]
@kkroboth I missed this...  I'm not sure if 9ee15e9 is relevant at this point. What do you think?

**Comment by kkroboth** [comment]
Looking at werkzeug run_simple(), it will wrap the application inside DebuggedApplication when use_debugger is true. However, the application is wrapped  before sent to run_simple() which will wrap it again.

https://github.com/pallets/werkzeug/blob/03faf0569861e9d8c8c94785ad5560f735ba72da/werkzeug/serving.py#L632

**Comment by tony** [comment]
@kkroboth I am a bit confused because we both made changes.

I think I missed this PR and went own making my own changes to the PR.

Where does this PR and https://github.com/django-extensions/django-extensions/pull/845 stand to you right now?

**Comment by kkroboth** [comment]
This PR can be closed.

When the runserver_plus runs, it wraps the application handler inside a DebuggedApplication before sending it to `run_simple()`.`run_simple()` also wraps the application if `use_debugger` is True.

I didn't find any problems when the application was wrapped twice.

**Pull request closed without merging**
